# Generated by Django 3.2.25 on 2025-07-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('type', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('issued_by', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('createdatetime', models.DateTimeField(auto_now_add=True)),
                ('short_description', models.CharField(blank=True, max_length=10000)),
            ],
        ),
    ]
