# Generated by Django 3.2.25 on 2025-07-24 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='createdatetime',
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.CharField(blank=True, max_length=50000),
        ),
        migrations.AddField(
            model_name='notification',
            name='createdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='createtime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
