# Generated by Django 3.2.25 on 2025-07-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250724_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='createtime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
