# Generated by Django 3.2.25 on 2025-07-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_notification_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='createtime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
