# Generated by Django 3.2.25 on 2025-07-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_notification_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='createdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='createtime',
            field=models.TimeField(auto_now=True),
        ),
    ]
