# Generated by Django 3.2.25 on 2025-07-24 12:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250724_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.notification_image_file_path),
        ),
    ]
